language: java
jdk:
  - oraclejdk8
script: ant JUnitTestSuite

notifications:
    slack:
      on_success: always
      on_failure: always
    email:
      recipients:
          - pablo.pastormunoz@alum.uca.es
      on_success: never
      on_failure: never
