
language: java
addons:
  apt:
    packages:
      - openjdk-6-jdk
jdk:
  - oraclejdk9
  - oraclejdk8
  - openjdk7
  - openjdk6

notifications:
    slack:
      on_success: always
      on_failure: always
    email:
      recipients:
          - pablo.pastormunoz@alum.uca.es
      on_success: never
      on_failure: never
